server:
  name: "project-api"
  addr: "0.0.0.0:80"
zap:
  debugFileName: "/srv/pms/logs/debug/project-debug.log"
  infoFileName: "/srv/pms/logs/info/project-info.log"
  warnFileName: "/srv/pms/logs/error/project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
etcd:
  addrs:
    - "etcd:2379"
