server:
  name: "project-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "D:\\Code\\python\\pms\\sever\\pms\\logs\\debug\\project-debug.log"
  infoFileName: "D:\\Code\\python\\pms\\sever\\pms\\logs\\info\\project-info.log"
  warnFileName: "D:\\Code\\python\\pms\\sever\\pms\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
mysql:
  username: "root"
  password: "1234"
  host: "127.0.0.1"
  port: 3306
  db: "msproject"