// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: room_service.proto

package room_type

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomService_RoomType_FullMethodName            = "/room.service.v1.RoomService/RoomType"
	RoomService_SaveRoomType_FullMethodName        = "/room.service.v1.RoomService/SaveRoomType"
	RoomService_UpdateRoomType_FullMethodName      = "/room.service.v1.RoomService/UpdateRoomType"
	RoomService_DeleteRoomType_FullMethodName      = "/room.service.v1.RoomService/DeleteRoomType"
	RoomService_HotelRoom_FullMethodName           = "/room.service.v1.RoomService/HotelRoom"
	RoomService_SaveHotelRoom_FullMethodName       = "/room.service.v1.RoomService/SaveHotelRoom"
	RoomService_UpdateHotelRoom_FullMethodName     = "/room.service.v1.RoomService/UpdateHotelRoom"
	RoomService_DeleteHotelRoom_FullMethodName     = "/room.service.v1.RoomService/DeleteHotelRoom"
	RoomService_RoomGuestStay_FullMethodName       = "/room.service.v1.RoomService/RoomGuestStay"
	RoomService_UpdateRoomGuestStay_FullMethodName = "/room.service.v1.RoomService/UpdateRoomGuestStay"
)

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomServiceClient interface {
	RoomType(ctx context.Context, in *RoomTypeMessage, opts ...grpc.CallOption) (*RoomTypeResponse, error)
	SaveRoomType(ctx context.Context, in *SaveRoomTypeMessage, opts ...grpc.CallOption) (*SaveRoomTypeResponse, error)
	UpdateRoomType(ctx context.Context, in *UpdateRoomTypeMessage, opts ...grpc.CallOption) (*UpdateRoomTypeResponse, error)
	DeleteRoomType(ctx context.Context, in *DeleteRoomTypeMessage, opts ...grpc.CallOption) (*DeleteRoomTypeResponse, error)
	HotelRoom(ctx context.Context, in *HotelRoomMessage, opts ...grpc.CallOption) (*HotelRoomResponse, error)
	SaveHotelRoom(ctx context.Context, in *SaveHotelRoomMessage, opts ...grpc.CallOption) (*SaveHotelRoomResponse, error)
	UpdateHotelRoom(ctx context.Context, in *UpdateHotelRoomMessage, opts ...grpc.CallOption) (*UpdateHotelRoomResponse, error)
	DeleteHotelRoom(ctx context.Context, in *DeleteHotelRoomMessage, opts ...grpc.CallOption) (*DeleteHotelRoomResponse, error)
	RoomGuestStay(ctx context.Context, in *RoomGuestStayMessage, opts ...grpc.CallOption) (*RoomGuestStayResponse, error)
	UpdateRoomGuestStay(ctx context.Context, in *UpdateRoomGuestStayMessage, opts ...grpc.CallOption) (*UpdateRoomGuestStayResponse, error)
}

type roomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomServiceClient(cc grpc.ClientConnInterface) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) RoomType(ctx context.Context, in *RoomTypeMessage, opts ...grpc.CallOption) (*RoomTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomTypeResponse)
	err := c.cc.Invoke(ctx, RoomService_RoomType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) SaveRoomType(ctx context.Context, in *SaveRoomTypeMessage, opts ...grpc.CallOption) (*SaveRoomTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRoomTypeResponse)
	err := c.cc.Invoke(ctx, RoomService_SaveRoomType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoomType(ctx context.Context, in *UpdateRoomTypeMessage, opts ...grpc.CallOption) (*UpdateRoomTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoomTypeResponse)
	err := c.cc.Invoke(ctx, RoomService_UpdateRoomType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DeleteRoomType(ctx context.Context, in *DeleteRoomTypeMessage, opts ...grpc.CallOption) (*DeleteRoomTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoomTypeResponse)
	err := c.cc.Invoke(ctx, RoomService_DeleteRoomType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) HotelRoom(ctx context.Context, in *HotelRoomMessage, opts ...grpc.CallOption) (*HotelRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotelRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_HotelRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) SaveHotelRoom(ctx context.Context, in *SaveHotelRoomMessage, opts ...grpc.CallOption) (*SaveHotelRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveHotelRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_SaveHotelRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateHotelRoom(ctx context.Context, in *UpdateHotelRoomMessage, opts ...grpc.CallOption) (*UpdateHotelRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHotelRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_UpdateHotelRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DeleteHotelRoom(ctx context.Context, in *DeleteHotelRoomMessage, opts ...grpc.CallOption) (*DeleteHotelRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHotelRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_DeleteHotelRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RoomGuestStay(ctx context.Context, in *RoomGuestStayMessage, opts ...grpc.CallOption) (*RoomGuestStayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomGuestStayResponse)
	err := c.cc.Invoke(ctx, RoomService_RoomGuestStay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoomGuestStay(ctx context.Context, in *UpdateRoomGuestStayMessage, opts ...grpc.CallOption) (*UpdateRoomGuestStayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoomGuestStayResponse)
	err := c.cc.Invoke(ctx, RoomService_UpdateRoomGuestStay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
// All implementations must embed UnimplementedRoomServiceServer
// for forward compatibility.
type RoomServiceServer interface {
	RoomType(context.Context, *RoomTypeMessage) (*RoomTypeResponse, error)
	SaveRoomType(context.Context, *SaveRoomTypeMessage) (*SaveRoomTypeResponse, error)
	UpdateRoomType(context.Context, *UpdateRoomTypeMessage) (*UpdateRoomTypeResponse, error)
	DeleteRoomType(context.Context, *DeleteRoomTypeMessage) (*DeleteRoomTypeResponse, error)
	HotelRoom(context.Context, *HotelRoomMessage) (*HotelRoomResponse, error)
	SaveHotelRoom(context.Context, *SaveHotelRoomMessage) (*SaveHotelRoomResponse, error)
	UpdateHotelRoom(context.Context, *UpdateHotelRoomMessage) (*UpdateHotelRoomResponse, error)
	DeleteHotelRoom(context.Context, *DeleteHotelRoomMessage) (*DeleteHotelRoomResponse, error)
	RoomGuestStay(context.Context, *RoomGuestStayMessage) (*RoomGuestStayResponse, error)
	UpdateRoomGuestStay(context.Context, *UpdateRoomGuestStayMessage) (*UpdateRoomGuestStayResponse, error)
	mustEmbedUnimplementedRoomServiceServer()
}

// UnimplementedRoomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServiceServer struct{}

func (UnimplementedRoomServiceServer) RoomType(context.Context, *RoomTypeMessage) (*RoomTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoomType not implemented")
}
func (UnimplementedRoomServiceServer) SaveRoomType(context.Context, *SaveRoomTypeMessage) (*SaveRoomTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRoomType not implemented")
}
func (UnimplementedRoomServiceServer) UpdateRoomType(context.Context, *UpdateRoomTypeMessage) (*UpdateRoomTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoomType not implemented")
}
func (UnimplementedRoomServiceServer) DeleteRoomType(context.Context, *DeleteRoomTypeMessage) (*DeleteRoomTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoomType not implemented")
}
func (UnimplementedRoomServiceServer) HotelRoom(context.Context, *HotelRoomMessage) (*HotelRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HotelRoom not implemented")
}
func (UnimplementedRoomServiceServer) SaveHotelRoom(context.Context, *SaveHotelRoomMessage) (*SaveHotelRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveHotelRoom not implemented")
}
func (UnimplementedRoomServiceServer) UpdateHotelRoom(context.Context, *UpdateHotelRoomMessage) (*UpdateHotelRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHotelRoom not implemented")
}
func (UnimplementedRoomServiceServer) DeleteHotelRoom(context.Context, *DeleteHotelRoomMessage) (*DeleteHotelRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHotelRoom not implemented")
}
func (UnimplementedRoomServiceServer) RoomGuestStay(context.Context, *RoomGuestStayMessage) (*RoomGuestStayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoomGuestStay not implemented")
}
func (UnimplementedRoomServiceServer) UpdateRoomGuestStay(context.Context, *UpdateRoomGuestStayMessage) (*UpdateRoomGuestStayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoomGuestStay not implemented")
}
func (UnimplementedRoomServiceServer) mustEmbedUnimplementedRoomServiceServer() {}
func (UnimplementedRoomServiceServer) testEmbeddedByValue()                     {}

// UnsafeRoomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServiceServer will
// result in compilation errors.
type UnsafeRoomServiceServer interface {
	mustEmbedUnimplementedRoomServiceServer()
}

func RegisterRoomServiceServer(s grpc.ServiceRegistrar, srv RoomServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomService_ServiceDesc, srv)
}

func _RoomService_RoomType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomTypeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_RoomType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomType(ctx, req.(*RoomTypeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_SaveRoomType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRoomTypeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).SaveRoomType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_SaveRoomType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).SaveRoomType(ctx, req.(*SaveRoomTypeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoomType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomTypeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoomType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_UpdateRoomType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoomType(ctx, req.(*UpdateRoomTypeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DeleteRoomType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomTypeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DeleteRoomType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_DeleteRoomType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DeleteRoomType(ctx, req.(*DeleteRoomTypeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_HotelRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotelRoomMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).HotelRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_HotelRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).HotelRoom(ctx, req.(*HotelRoomMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_SaveHotelRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveHotelRoomMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).SaveHotelRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_SaveHotelRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).SaveHotelRoom(ctx, req.(*SaveHotelRoomMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateHotelRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHotelRoomMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateHotelRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_UpdateHotelRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateHotelRoom(ctx, req.(*UpdateHotelRoomMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DeleteHotelRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHotelRoomMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DeleteHotelRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_DeleteHotelRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DeleteHotelRoom(ctx, req.(*DeleteHotelRoomMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RoomGuestStay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomGuestStayMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomGuestStay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_RoomGuestStay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomGuestStay(ctx, req.(*RoomGuestStayMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoomGuestStay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomGuestStayMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoomGuestStay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_UpdateRoomGuestStay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoomGuestStay(ctx, req.(*UpdateRoomGuestStayMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomService_ServiceDesc is the grpc.ServiceDesc for RoomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "room.service.v1.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RoomType",
			Handler:    _RoomService_RoomType_Handler,
		},
		{
			MethodName: "SaveRoomType",
			Handler:    _RoomService_SaveRoomType_Handler,
		},
		{
			MethodName: "UpdateRoomType",
			Handler:    _RoomService_UpdateRoomType_Handler,
		},
		{
			MethodName: "DeleteRoomType",
			Handler:    _RoomService_DeleteRoomType_Handler,
		},
		{
			MethodName: "HotelRoom",
			Handler:    _RoomService_HotelRoom_Handler,
		},
		{
			MethodName: "SaveHotelRoom",
			Handler:    _RoomService_SaveHotelRoom_Handler,
		},
		{
			MethodName: "UpdateHotelRoom",
			Handler:    _RoomService_UpdateHotelRoom_Handler,
		},
		{
			MethodName: "DeleteHotelRoom",
			Handler:    _RoomService_DeleteHotelRoom_Handler,
		},
		{
			MethodName: "RoomGuestStay",
			Handler:    _RoomService_RoomGuestStay_Handler,
		},
		{
			MethodName: "UpdateRoomGuestStay",
			Handler:    _RoomService_UpdateRoomGuestStay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room_service.proto",
}
